version: '3'

services:
  redis-1:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redubble-network

  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-1
    networks:
      - redubble-network

networks:
  redubble-network:
    driver: bridge